package constants

const INACC_LINKS_MAX_CAP = 300
const INACC_LINKS_INIT_CAP = 20
const CONCURRENT_GOROUTINE_LIMIT = 20
const REQUEST_TIMEOUT_SECONDS = 5
const MB_IN_BYTES = 1048576
const MAX_ALLOWED_HTML_SIZE = 5 * MB_IN_BYTES

const SERVER_PORT = 3000
