name: Dev Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  

jobs:
  deploy:
    name: Dev Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

      - name: Run golangci-lint
        run: golangci-lint run

      - name: Build the application
        run: go build -o bin/app ./cmd

      # - name: Run tests
      #   run: go test ./...

      # - name: Deploy to development environment
      #   run: |
      #     echo "Deploying to development environment..."
      #     # Add your deployment commands here
